# Generated by Django 5.2.1 on 2025-06-20 22:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_name', models.CharField(default='مساحة العمل', max_length=100, verbose_name='اسم المكان')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, verbose_name='سعر الساعة الافتراضي')),
                ('currency', models.CharField(default='جنيه', max_length=10, verbose_name='العملة')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الضريبة')),
                ('warning_minutes', models.IntegerField(default=10, verbose_name='تحذير قبل انتهاء الجلسة (بالدقائق)')),
            ],
            options={
                'verbose_name': 'إعدادات',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
