# Generated by Django 5.2.1 on 2025-06-27 13:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='خصم'),
        ),
        migrations.AddField(
            model_name='session',
            name='total_before_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المبلغ قبل الخصم'),
        ),
        migrations.AlterField(
            model_name='session',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='المبلغ بعد الخصم'),
        ),
    ]
