# Generated by Django 5.2.1 on 2025-06-29 20:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_invoice_discount_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='log_type',
            field=models.CharField(choices=[('customer_created', 'إنشاء عميل جديد'), ('session_started', 'بدء جلسة'), ('session_ended', 'انتهاء جلسة'), ('order_created', 'طلب جديد'), ('invoice_generated', 'توليد فاتورة'), ('expense_added', 'إضافة مصروف')], db_index=True, max_length=30, verbose_name='نوع الحدث'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='معرف العميل'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(choices=[('electricity', 'كهرباء'), ('water', 'مياه'), ('rent', 'إيجار'), ('internet', 'إنترنت'), ('maintenance', 'صيانة'), ('supplies', 'مستلزمات'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='نوع المصروف'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(db_index=True, default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(db_index=True, default='مشروبات', max_length=50, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='session',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('open', 'مفتوح'), ('timed', 'محدد بوقت')], db_index=True, default='open', max_length=10, verbose_name='نوع الجلسة'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='وقت البداية'),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('completed', 'مكتمل'), ('expired', 'منتهي')], db_index=True, default='active', max_length=20, verbose_name='الحالة'),
        ),
    ]
